config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root to: 'municipes#index'
  resources :municipes, except: [:destroy] do
    patch 'toggle_status', on: :member
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :municipe
  validates :cep, correios_cep: true
  validates :cep, :street, :neighborhood, :city, :state, presence: true

  def self.ransackable_attributes(_auth_object = nil)
    %w[street state city]
  end

  def self.ransackable_associations(_auth_object = nil)
    %w[municipe]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/municipe.rb
class Municipe < ApplicationRecord
  has_one :address, dependent: :destroy
  accepts_nested_attributes_for :address
  enum status: { active: 0, inactive: 1 }
  has_one_attached :photo

  validates :cpf, cpf: true
  validates :cns, cns: true
  validates :birth_date, birth_date: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :phone_number, phone: true

  validates :full_name, :cpf, :cns, :email, :birth_date, :phone_number, :photo, :status,
            presence: true

  def self.ransackable_attributes(_auth_object = nil)
    %w[full_name cpf cns email phone_number status]
  end

  def self.ransackable_associations(_auth_object = nil)
    %w[address]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/municipes_controller.rb
class MunicipesController < ApplicationController
  before_action :set_municipe, only: %i[show edit update toggle_status]

  def index
    @q = Municipe.ransack(params[:q])
    @q.sorts = 'full_name asc' if @q.sorts.empty?
    @municipes = @q.result.includes(:address).page(params[:page]).per(params[:per_page] || 6)
  end

  def show; end

  def new
    @municipe = Municipe.new
    @municipe.build_address
  end

  def create
    @municipe = Municipe.new(municipe_params)

    if @municipe.save
      Notification::MessageDeliverer.call(@municipe, :create)
      redirect_to @municipe, notice: t('.create')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @municipe.update(municipe_params)
      Notification::MessageDeliverer.call(@municipe, :update)
      redirect_to @municipe, notice: t('.update')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def toggle_status
    update_status!

    if @municipe.save
      Notification::MessageDeliverer.call(@municipe, :toggle_status)
      redirect_to root_path, notice: t('.toggle_status.success')
    else
      redirect_to municipe_path(@municipe), status: :unprocessable_entity, notice: t('.toggle_status.failure')
    end
  end

  private

  def set_municipe
    @municipe = Municipe.find(params[:id])
  end

  def municipe_params
    params.require(:municipe).permit(:full_name, :cpf, :cns, :email, :email_confirmation, :birth_date, :phone_number,
                                     :photo, :status,
                                     address_attributes: %i[cep street complement neighborhood city state ibge_code])
  end

  def update_status!
    @municipe.status = @municipe.status == 'active' ? 'inactive' : 'active'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/municipes_helper.rb
module MunicipesHelper
  def phone_formatter(phone_number)
    cleaned_number = phone_number.gsub(/\D/, '')
    "(#{cleaned_number[0..1]}) #{cleaned_number[2..6]}-#{cleaned_number[7..10]}"
  end

  def error_class(municipe, attribute)
    municipe.errors.include?(attribute) ? 'border-red-500' : 'border'
  end

  def error_message(municipe, attribute)
    return unless municipe.errors.include?(attribute)

    content_tag(:div, municipe.errors.full_messages_for(attribute).join(', '), class: 'text-red-500 text-sm')
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JedisProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="h-dvh">
    <main class="container mx-auto px-4 sm:px-8">
      <%= yield %>
    </main>
  </body>
</html>

app/views/municipes/_municipe.html.erb
<tr id="<%= dom_id municipe %>" class="bg-gray-100 hover:bg-white">
  <td class="px-5 py-2 border-b">
    <%= image_tag municipe.photo, class: 'w-20 h-20 object-cover mx-auto rounded' %>
  </td>
  <td class="px-5 py-2 border-b"><%= municipe.full_name %></td>
  <td class="px-5 py-2 border-b"><%= municipe.cpf %></td>
  <td class="px-5 py-2 border-b"><%= municipe.cns %></td>
  <td class="px-5 py-2 border-b"><%= municipe.address.state %></td>
  <td class="px-5 py-2 border-b"><%= municipe.address.city %></td>
  <td class="px-5 py-2 border-b"><%= phone_formatter(municipe.phone_number) %></td>
  <td class="px-5 py-2 border-b">
    <% status_color_class = municipe.inactive? ? 'bg-red-500' : 'bg-blue-500' %>
    <span class="inline-block py-1 px-2 rounded text-white text-center text-xs font-semibold <%= status_color_class %> w-16">
    <%= t("activerecord.attributes.municipe.status.#{municipe.status}") %>
  </span>
  </td>


  <td class="px-5 py-2 border-b">
    <%= link_to t('.show'), municipe, class: 'text-blue-500 hover:underline mr-2' %>
    <%= link_to t('.edit'), edit_municipe_path(municipe), class: 'text-green-500 hover:underline mr-2' %>
    <%= button_to t('.toggle_status'), toggle_status_municipe_path(municipe), method: :patch, data: { turbo_action: 'replace', turbo_confirm: t('.toggle_confirm') }, class: 'text-orange-500 hover:underline' %>
  </td>
</tr>

app/views/municipes/edit.html.erb
<div class="min-h-screen min-w-full p-6 bg-gray-100 flex flex-col items-center justify-center">
  <h1 class="font-medium text-lg text-gray-600"><%= t('.title') %></h1>

  <%= render "form", municipe: @municipe %>

  <div class="flex gap-2">
    <%= link_to t('.show'), @municipe, class: 'flex items-center h-10 border mt-1 rounded px-4 w-full bg-gray-50 text-center text-gray-700 hover:bg-gray-200 transition duration-300 ease-in-out' %>
    <%= link_to t('.back'), municipes_path, class: 'flex items-center h-10 border mt-1 rounded px-4 w-full bg-gray-50 text-center text-gray-700 hover:bg-gray-200 transition duration-300 ease-in-out' %>
  </div>
</div>

app/views/municipes/index.html.erb
<div class="py-8">
  <div>
    <h2 class="text-2xl font-semibold leading-tight"><%= t('.title') %></h2>
  </div>
  <div class="flex justify-between items-center">
    <div class="my-2 flex sm:flex-row flex-col">
      <%= search_form_for @q, url: municipes_path, method: 'get', class:'flex' do |f| %>
        <div class="relative">
          <select class="appearance-none h-full rounded-l border block appearance-none w-full bg-white border-gray-600 text-gray-700 py-2 px-4 pr-8 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" name="per_page" onchange="this.form.submit()">
            <option value="2" <%= 'selected' if params[:per_page] == '2' %>>2</option>
            <option value="5" <%= 'selected' if params[:per_page] == '5' %>>5</option>
            <option value="10" <%= 'selected' if params[:per_page] == '10' %>>10</option>
            <option value="20" <%= 'selected' if params[:per_page] == '20' %>>20</option>
          </select>
        </div>

        <div class="group relative">
        <button type="button" class="flex appearance-none h-full rounded-r border-t sm:rounded-r-none sm:border-r-0 border-r border-b block appearance-none w-full bg-white border-gray-400 text-gray-700 py-2 px-4 pr-8 leading-tight focus:outline-none focus:border-l focus:border-r focus:bg-white focus:border-gray-500">
          <%= t('.filter') %>
          <svg class="w-4 h-4 ml-2 -mr-1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M10 12l-5-5h10l-5 5z" />
          </svg>
        </button>
        <div class="absolute left-0 w-40 origin-top-left bg-white divide-y divide-gray-100 rounded-md shadow-lg opacity-0 invisible group-hover:opacity-100 group-hover:visible transition duration-300">
          <div class="py-1">
            <ul>
              <%= link_to municipes_path(q: (params[:q] ? params[:q].to_unsafe_h : {}).merge(status_eq: :active, status_not_eq: nil)), class: "hover:bg-gray-100" do %>
                <li class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">
                  <%= t('.actives') %>
                </li>
              <% end %>
              <%= link_to municipes_path(q: (params[:q] ? params[:q].to_unsafe_h : {}).merge(status_eq: nil, status_not_eq: :active)) do %>
                <li class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">
                  <%= t('.inactives') %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>


        <div class="block relative h-full rounded-r rounded-l sm:rounded-l-none sm:border-l-0 border border-gray-400 border-b">
          <%= f.label t('.search_info'), class: 'hidden' %>
          <span class="h-full absolute inset-y-0 left-0 flex items-center pl-2">
            <svg viewBox="0 0 24 24" class="h-4 w-4 fill-current text-gray-500">
              <path d="M10 4a6 6 0 100 12 6 6 0 000-12zm-8 6a8 8 0 1114.32 4.906l5.387 5.387a1 1 0 01-1.414 1.414l-5.387-5.387A8 8 0 012 10z"></path>
            </svg>
          </span>
          <%= f.search_field :full_name_or_cpf_or_cns_or_email_or_phone_number_or_address_state_or_address_city_cont, placeholder: t('.search'), class: 'appearance-none border-0 h-full pl-8 pr-6 py-2 w-full bg-white text-sm placeholder-gray-400 text-gray-700 focus:bg-white focus:placeholder-gray-600 focus:text-gray-700 focus:outline-none' %>
        </div>
        <%= f.submit class: 'cursor-pointer p-2.5 ms-2 text-sm font-medium text-white bg-gray-700 rounded-lg border border-gray-700 hover:bg-gray-800 focus:ring-4 focus:outline-none focus:ring-gray-300 dark:bg-gray-600 dark:hover:bg-gray-700 dark:focus:ring-gray-800' do %>
          <svg class="w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
          </svg>
          <span class="sr-only"><%= t('.search') %></span>
        <% end %>

      <% end %>
    </div>
    <%= link_to new_municipe_path, class: 'flex gap-2 items-center p-2.5 ms-2 text-sm font-medium text-white bg-gray-700 rounded-lg border border-gray-700 hover:bg-gray-800 focus:ring-4 focus:outline-none focus:ring-gray-300 dark:bg-gray-600 dark:hover:bg-gray-700 dark:focus:ring-gray-800' do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M18 7.5v3m0 0v3m0-3h3m-3 0h-3m-2.25-4.125a3.375 3.375 0 1 1-6.75 0 3.375 3.375 0 0 1 6.75 0ZM3 19.235v-.11a6.375 6.375 0 0 1 12.75 0v.109A12.318 12.318 0 0 1 9.374 21c-2.331 0-4.512-.645-6.374-1.766Z" />
      </svg>
      <%= t('.add_municipe') %>
  <% end %>
  </div>

  <div class="-mx-4 sm:-mx-8 px-4 sm:px-8 py-4 overflow-x-auto">
    <div class="inline-block min-w-full shadow rounded-lg overflow-hidden">
      <table class="min-w-full leading-normal">
        <thead>
        <tr>
          <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-center text-xs font-semibold text-gray-600 uppercase tracking-wider">
            <%= I18n.t('activerecord.attributes.municipe.photo') %>
          </th>
          <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
            <%= sort_link(@q, :full_name, I18n.t('activerecord.attributes.municipe.full_name')) %>
          </th>
          <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
            <%= sort_link(@q, :cpf, I18n.t('activerecord.attributes.municipe.cpf')) %>
          </th>
          <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
            <%= sort_link(@q, :cns, I18n.t('activerecord.attributes.municipe.cns')) %>
          </th>
          <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
            <%= I18n.t('activerecord.attributes.address.state') %>
          </th>
          <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
            <%= I18n.t('activerecord.attributes.address.city') %>
          </th>
          <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
            <%= I18n.t('activerecord.attributes.municipe.phone_number') %>
          </th>
          <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
            <%= t('.status') %>
          </th>
          <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-center text-xs font-semibold text-gray-600 uppercase tracking-wider">
            <%= t('.actions') %>
          </th>
        </tr>
        </thead>
        <tbody>
        <%= render @municipes %>
        </tbody>
      </table>

      <div class="flex items-center justify-between m-6">
        <%= link_to_prev_page @municipes, '< Página anterior', class: 'flex items-center px-5 py-2 text-sm text-gray-700 capitalize transition-colors duration-200 bg-white border rounded-md gap-x-2 hover:bg-gray-100 dark:bg-gray-900 dark:text-gray-200 dark:border-gray-700 dark:hover:bg-gray-800' %>
        <%= link_to_next_page @municipes, 'Próxima página >', class: 'flex items-center self-center px-5 py-2 text-sm text-gray-700 capitalize transition-colors duration-200 bg-white border rounded-md gap-x-2 hover:bg-gray-100 dark:bg-gray-900 dark:text-gray-200 dark:border-gray-700 dark:hover:bg-gray-800' %>
      </div>
    </div>
  </div>
</div>

app/views/municipes/new.html.erb
<div class="min-h-screen min-w-full p-6 flex flex-col items-center justify-center">
  <h1 class="font-medium text-lg text-gray-600"><%= t('.title') %></h1>

  <%= render "form", municipe: @municipe %>

  <div class="flex gap-2">
    <%= link_to t('.back'), municipes_path, class: 'flex items-center h-10 border mt-1 rounded px-4 w-full bg-gray-50 text-center text-gray-700 hover:bg-gray-200 transition duration-300 ease-in-out' %>
  </div>
</div>

app/views/municipes/show.html.erb
<div class="h-full p-8">
  <div class="bg-white rounded-lg shadow-xl pb-8">
    <div class="w-full h-[250px]">
<!--      <img src="https://vojislavd.com/ta-template-demo/assets/img/profile-background.jpg" class="w-full h-full rounded-tl-lg rounded-tr-lg">-->
    <%= image_tag 'unsplash_img.jpg', class: 'w-full h-full rounded-tl-lg rounded-tr-lg' %>
    </div>

    <div class="flex flex-col items-center -mt-20">
      <%= image_tag @municipe.photo, class: 'w-40 border-4 border-white rounded-full' if @municipe.photo.attached? %>
      <div class="flex items-center space-x-2 mt-2">
        <p class="text-2xl"><%= @municipe.full_name %></p>
        <% if @municipe.status == 'active' %>
          <span class="bg-blue-500 rounded-full p-1">
            <svg xmlns="http://www.w3.org/2000/svg" class="text-gray-100 h-2.5 w-2.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="4" d="M5 13l4 4L19 7"></path>
            </svg>
          </span>
        <% else %>
          <span class="bg-red-600 rounded-full p-1">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4 text-gray-100">
              <path stroke-linecap="round" stroke-linejoin="round" d="M18.364 18.364A9 9 0 0 0 5.636 5.636m12.728 12.728A9 9 0 0 1 5.636 5.636m12.728 12.728L5.636 5.636" />
            </svg>
          </span>
        <% end %>
      </div>
      <p class="text-gray-700"><%= @municipe.email %></p>
      <p class="text-sm text-gray-500"><%= @municipe.address.city %>, <%= @municipe.address.state %></p>
    </div>
    <div class="flex-1 flex flex-col items-center lg:items-end justify-end px-8 mt-2">
      <div class="flex items-center space-x-4 mt-2">
      </div>
    </div>
  </div>

  <div class="my-4 flex flex-col 2xl:flex-row space-y-4 2xl:space-y-0 2xl:space-x-2">
    <div class="w-full flex gap-2">
      <div class="flex-1 bg-white rounded-lg shadow-xl p-6">
        <h4 class="text-xl text-gray-900 font-bold"><%= t '.personal_info' %></h4>
        <ul class="mt-2 text-gray-700">
          <li><%= I18n.t('activerecord.attributes.municipe.full_name') %>: <%= @municipe.full_name %></li>
          <li><%= I18n.t('activerecord.attributes.municipe.cpf') %>: <%= @municipe.cpf %></li>
          <li><%= I18n.t('activerecord.attributes.municipe.cns') %>: <%= @municipe.cns %></li>
          <li><%= I18n.t('activerecord.attributes.municipe.email') %>: <%= @municipe.email %></li>
          <li><%= I18n.t('activerecord.attributes.municipe.birth_date') %>: <%= I18n.l(@municipe.birth_date) %></li>
          <li><%= I18n.t('activerecord.attributes.municipe.phone_number') %>: <%= phone_formatter(@municipe.phone_number) %></li>
          <li><%= t '.status' %>: <%= t("activerecord.attributes.municipe.status.#{@municipe.status}") %></li>
          <%= button_to t('.toggle_status'), toggle_status_municipe_path(@municipe), method: :patch, data: { turbo_action: 'replace' }, class: 'hover:underline' %>
        </ul>
      </div>
      <div class="flex-1 bg-white rounded-lg shadow-xl p-6">
        <h4 class="text-xl text-gray-900 font-bold"><%= t '.address_info' %></h4>
        <ul class="mt-2 text-gray-700">
          <li><%= I18n.t('activerecord.attributes.address.city') %>: <%= @municipe.address.city %></li>
          <li><%= I18n.t('activerecord.attributes.address.state') %>: <%= @municipe.address.state %></li>
          <li><%= I18n.t('activerecord.attributes.address.neighborhood') %>: <%= @municipe.address.neighborhood %></li>
          <li><%= I18n.t('activerecord.attributes.address.street') %>: <%= @municipe.address.street %></li>
          <li><%= I18n.t('activerecord.attributes.address.complement') %>: <%= @municipe.address.complement %></li>
          <li><%= I18n.t('activerecord.attributes.address.cep') %>: <%= @municipe.address.cep %></li>
          <li><%= I18n.t('activerecord.attributes.address.ibge_code') %>: <%= @municipe.address.ibge_code %></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="flex gap-2 justify-center">
    <%= link_to t('.edit'), edit_municipe_path(@municipe), class: 'flex items-center justify-center h-10 border mt-1 rounded px-4 py-2 w-52 bg-gray-50 text-center text-gray-700 hover:bg-gray-200 transition duration-300 ease-in-out' %>
    <%= link_to t('.back'), municipes_path, class: 'flex items-center h-10 border mt-1 rounded px-4 py-2 w-52 bg-gray-50 text-center text-gray-700 hover:bg-gray-200 transition duration-300 ease-in-out' %>
  </div>
</div>